import 'fake-indexeddb/auto';
import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { extractSections, fingerprintPdf, type PdfDocumentLike } from '../lib/pdf/extract';
import { importPdfSections, pdfScopeKey } from '../lib/pdf/import';
import { GraphDatabase } from '../lib/storage/database';
import { GraphRepository } from '../lib/storage/repository';

// tests/fixtures/demo-paper.pdf is generated by make-demo-pdf.py. It is a
// labeled synthetic fixture, not a real paper.
const fixture = fileURLToPath(new URL('./fixtures/demo-paper.pdf', import.meta.url));

async function openFixture(): Promise<{ document: PdfDocumentLike; bytes: Uint8Array }> {
  const pdfjs = await import('pdfjs-dist/legacy/build/pdf.mjs');
  const bytes = new Uint8Array(await readFile(fixture));
  const document = await pdfjs.getDocument({
    data: bytes.slice(),
    useWorkerFetch: false,
  }).promise;
  return { document: document as unknown as PdfDocumentLike, bytes };
}

test('a fingerprint is stable, content-addressed, and shaped for the stored locator', async () => {
  const bytes = new Uint8Array(await readFile(fixture));
  const first = await fingerprintPdf(bytes);
  const second = await fingerprintPdf(new Uint8Array(await readFile(fixture)));

  expect(first).toBe(second);
  expect(first).toMatch(/^[a-f0-9]{64}$/);

  const changed = new Uint8Array(bytes);
  changed[changed.length - 1] = changed[changed.length - 1]! ^ 0xff;
  expect(await fingerprintPdf(changed)).not.toBe(first);
});

test('embedded bookmarks become sections with real pages and preserved nesting', async () => {
  const { document, bytes } = await openFixture();
  const extraction = await extractSections(document, await fingerprintPdf(bytes));

  expect(extraction.origin).toBe('outline');
  expect(extraction.pageCount).toBe(3);

  const byTitle = new Map(extraction.sections.map((s) => [s.title, s]));
  expect([...byTitle.keys()].sort()).toEqual(['Findings', 'Methods', 'Overview', 'Scope and Definitions']);

  // Zero-based page indices, matching the stored locator.
  expect(byTitle.get('Overview')!.pageIndex).toBe(0);
  expect(byTitle.get('Methods')!.pageIndex).toBe(1);
  expect(byTitle.get('Findings')!.pageIndex).toBe(2);

  // The nested bookmark keeps its parent rather than being flattened.
  const nested = byTitle.get('Scope and Definitions')!;
  expect(nested.parentId).toBe(byTitle.get('Overview')!.id);
  expect(nested.pageIndex).toBe(0);

  // Top-level bookmarks have no parent.
  expect(byTitle.get('Methods')!.parentId).toBeUndefined();
});

test('same-page sections stay distinguishable so their destinations do not collide', async () => {
  const { document, bytes } = await openFixture();
  const extraction = await extractSections(document, await fingerprintPdf(bytes));

  const overview = extraction.sections.find((s) => s.title === 'Overview')!;
  const nested = extraction.sections.find((s) => s.title === 'Scope and Definitions')!;

  // Both sit on page 1; only the position separates their stored locators.
  expect(nested.pageIndex).toBe(overview.pageIndex);
  expect(nested.point!.y).not.toBe(overview.point!.y);
  for (const section of extraction.sections) {
    expect(section.point!.x).toBeGreaterThanOrEqual(0);
    expect(section.point!.y).toBeLessThanOrEqual(1);
  }
  expect(extraction.mergedDuplicates).toBe(0);
});

test('a document without bookmarks falls back to labeled heading proposals', async () => {
  const { document } = await openFixture();
  // Same real document, outline withheld, so the fallback path is exercised.
  // Delegate rather than spread: PDF.js methods live on the prototype.
  const withoutOutline: PdfDocumentLike = {
    numPages: document.numPages,
    getOutline: async () => null,
    getDestination: (id) => document.getDestination(id),
    getPageIndex: (ref) => document.getPageIndex(ref),
    getPage: (n) => document.getPage(n),
  };
  const extraction = await extractSections(withoutOutline, 'f'.repeat(64));

  expect(extraction.origin).toBe('heading');
  expect(extraction.sections.length).toBeGreaterThan(0);
  // Every proposal is labeled, so it cannot be mistaken for the author's outline.
  expect(extraction.sections.every((s) => s.origin === 'heading')).toBe(true);
  expect(extraction.sections.map((s) => s.title)).toContain('Overview');
});

test('a malformed destination skips its section instead of failing the document', async () => {
  const { document } = await openFixture();
  const broken: PdfDocumentLike = {
    numPages: document.numPages,
    getPage: (n) => document.getPage(n),
    getOutline: async () => [
      { title: 'Good', dest: [0, { name: 'XYZ' }, 72, 720, 0] },
      { title: 'Broken', dest: 'missing-named-destination' },
    ],
    getDestination: async () => null,
    getPageIndex: async () => 0,
  };
  const extraction = await extractSections(broken, 'a'.repeat(64));

  expect(extraction.sections.map((s) => s.title)).toEqual(['Good']);
});

test('extracted sections store as a real graph with nesting and stable IDs', async () => {
  const { document, bytes } = await openFixture();
  const extraction = await extractSections(document, await fingerprintPdf(bytes));
  const scoped = importPdfSections(extraction, 'Campus Wayfinding Study');

  expect(scoped.scopeKey).toBe(pdfScopeKey(extraction.fingerprint));
  // A local paper is not scoped to a Google account.
  expect(scoped.accountKey).toBe('local');

  const db = new GraphDatabase('graphnav-pdf-' + crypto.randomUUID());
  const repo = new GraphRepository(db);
  try {
    const graph = await repo.createGraph(scoped.title, crypto.randomUUID(), 'import');
    await repo.refreshScope(graph.id, graph.contentRevision, {
      scopeKey: scoped.scopeKey,
      accountKey: scoped.accountKey,
      complete: scoped.complete,
      items: scoped.items,
    });

    const snapshot = await repo.readGraph(graph.id);
    // The document plus its four bookmarked sections.
    expect(snapshot.nodes).toHaveLength(5);
    expect(snapshot.relationships).toHaveLength(4);

    const byTitle = new Map(snapshot.nodes.map((n) => [n.baseLabel, n]));
    const overview = byTitle.get('Overview')!;
    const nested = byTitle.get('Scope and Definitions')!;

    // The nested bookmark hangs off Overview, not off the document.
    const nestedEdge = snapshot.relationships.find((r) => r.memberNodeIds.includes(nested.id))!;
    expect(nestedEdge.memberNodeIds).toContain(overview.id);
    expect(nestedEdge.kind).toBe('contains');

    // Every section keeps a real page destination.
    for (const node of snapshot.nodes) {
      expect(node.locator?.kind).toBe('pdf');
      if (node.locator?.kind === 'pdf') {
        expect(node.locator.fingerprint).toBe(extraction.fingerprint);
        expect(node.locator.pageIndex).toBeGreaterThanOrEqual(0);
      }
    }

    // Re-importing the same paper must not duplicate its sections.
    const again = await repo.readGraph(graph.id);
    await repo.refreshScope(graph.id, again.graph.contentRevision, {
      scopeKey: scoped.scopeKey,
      accountKey: scoped.accountKey,
      complete: scoped.complete,
      items: scoped.items,
    });
    const after = await repo.readGraph(graph.id);
    expect(after.nodes).toHaveLength(5);
    expect(after.nodes.map((n) => n.id).sort()).toEqual(snapshot.nodes.map((n) => n.id).sort());
  } finally {
    await db.delete();
  }
});

test('the demo paper itself extracts with three levels of nesting', async () => {
  // demo/GraphNav-demo-paper.pdf is the artifact used in the walkthrough, so it
  // is checked here rather than trusted from a one-off run.
  const pdfjs = await import('pdfjs-dist/legacy/build/pdf.mjs');
  const demoPath = fileURLToPath(new URL('../demo/GraphNav-demo-paper.pdf', import.meta.url));
  const bytes = new Uint8Array(await readFile(demoPath));
  const document = await pdfjs.getDocument({ data: bytes.slice(), useWorkerFetch: false }).promise;

  const extraction = await extractSections(document as unknown as PdfDocumentLike, await fingerprintPdf(bytes));

  expect(extraction.origin).toBe('outline');
  expect(extraction.pageCount).toBe(6);
  expect(extraction.mergedDuplicates).toBe(0);

  const byTitle = new Map(extraction.sections.map((s) => [s.title, s]));
  const byId = new Map(extraction.sections.map((s) => [s.id, s]));

  // Well past the three jump targets M4-B requires.
  expect(extraction.sections.length).toBeGreaterThanOrEqual(3);

  // Three levels deep: Methods > Findings > The Single Sign Intervention.
  const findings = byTitle.get('Findings')!;
  const intervention = byTitle.get('The Single Sign Intervention')!;
  expect(byId.get(findings.parentId!)!.title).toBe('Methods');
  expect(byId.get(intervention.parentId!)!.title).toBe('Findings');

  // Each section lands on its own page, so the jumps are distinguishable.
  const pages = extraction.sections.map((s) => s.pageIndex);
  expect(new Set(pages).size).toBe(pages.length);

  // A top-level section has no parent.
  expect(byTitle.get('Overview')!.parentId).toBeUndefined();
});
